Shell formatter/linter fixes
Shellfmt setting:
 - Switch cases will be indented
 - Keep column alignment
 - Unix line separator

diff --git a/borgbackup-job b/borgbackup-job
--- a/borgbackup-job
+++ b/borgbackup-job
@@ -1,9 +1,9 @@
 #!/bin/bash
 
 PS4='+(${LINENO}) ' # add linenumbers to the trace when run with 'bash -x'
-NAME=$(basename $0)
-show_help () {
-  cat << EOM | sed -e's/^  //'
+NAME=$(basename "$0")
+show_help()  {
+  cat <<EOM  | sed -e's/^  //'
   Usage: $NAME [OPTION]... [PATHS_TO_BACKUP]
   Create backup with Borg
 
@@ -48,7 +48,7 @@ die() {
 abort() {
   # exits with exit code 2 and message on stderr, without timestamp
   # for user messages on commandline, i.e. at startup failure, where timestamp is ugly
-  if [[ -n $1 ]];then
+  if [[ -n $1 ]]; then
     printf "%s\n" "$*" >&2
   fi
   exit 2
@@ -93,32 +93,32 @@ init() {
   dry_run=false
   while true; do
     case $1 in
-    '--envfile')
+      '--envfile')
         [[ ${2:0:1} != '-' ]] || abort "$1 requires a filename argument"
         envfile="$2"
         shift 2
-      ;;
-    '--exclude')
+        ;;
+      '--exclude')
         [[ ${2:0:1} != '-' ]] || abort "$1 requires an argument"
         excludes_on_cmdline+=("$2")
         shift 2
-      ;;
-    '--dry-run')
+        ;;
+      '--dry-run')
         dry_run=true
         shift
-      ;;
-    '--help')
+        ;;
+      '--help')
         show_help
         die 0
-      ;;
-    '--')   # Separator between optional and positional parameters
+        ;;
+      '--') # Separator between optional and positional parameters
         shift
         break
-      ;;
+        ;;
     esac
   done
 
-  paths_on_cmdline=( "$@" )
+  paths_on_cmdline=("$@")
   set --
 
   source_conf_file "$envfile"
@@ -128,7 +128,7 @@ init() {
 
   # PATHS_TO_BACKUP can come from $envfile, but files on command line overrides
   if [[ ${#paths_on_cmdline[*]} -gt 0 ]]; then
-    PATHS_TO_BACKUP=( "${paths_on_cmdline[@]}" )
+    PATHS_TO_BACKUP=("${paths_on_cmdline[@]}")
   fi
   [[ ${#PATHS_TO_BACKUP[*]} -eq 0 ]] && abort "invalid usage: nothing to backup (no files specified, and environment PATHS_TO_BACKUP is not set)"
 
@@ -176,24 +176,25 @@ fi
 
 info "Starting borg backup"
 
-borg create                       \
-     --stats                      \
-     --show-version               \
-     --show-rc                    \
-     --filter AME                 \
-     --list                       \
-     $EXCL                        \
-     ::'{now:%Y-%m-%dT%H:%M:%S}'  \
-     "${PATHS_TO_BACKUP[@]}"      \
-  || die $? "borg create ended with $(warning_or_error $?). Not pruning repository"
+# shellcheck disable=SC2086
+borg create \
+  --stats \
+  --show-version \
+  --show-rc \
+  --filter    AME \
+  --list \
+  $EXCL \
+  ::'{now:%Y-%m-%dT%H:%M:%S}' \
+  "${PATHS_TO_BACKUP[@]}" ||
+  die $? "borg create ended with $(warning_or_error $?). Not pruning repository"
 
 info "Pruning repository"
 
-borg prune             \
-    --list             \
-    --show-rc          \
-    --keep-daily    14 \
-    --keep-weekly   4  \
-    --keep-monthly  12 \
-    --keep-yearly   5  \
-  || die $? "borg prune ended with $(warning_or_error $?)."
+borg prune \
+  --list \
+  --show-rc \
+  --keep-daily   14 \
+  --keep-weekly   4 \
+  --keep-monthly 12 \
+  --keep-yearly   5 ||
+  die $? "borg prune ended with $(warning_or_error $?)."
