pre/post-backup hooks in borgbackup-job

diff --git a/borgbackup-job b/borgbackup-job
--- a/borgbackup-job
+++ b/borgbackup-job
@@ -20,6 +20,7 @@ Examples:
 EOM
 }
 
+USER_BACKUP_CONFDIR="${HOME}/.borgbackup"
 
 # Some helpers and error handling
 info() { [[ -n $1 ]] && printf "\n%(%F_%T)T %s\n" -1 "$*" >&2; }
@@ -28,11 +29,23 @@ abort() { [[ -n $1 ]] && printf "%s\n" "$*" >&2; exit 2 ;}
 warning_or_error() { code=$1; ret="warning"; [[ $code -gt 1 ]] && ret="error"; echo $ret; }
 trap 'die 2 "Backup interrupted"' INT TERM
 
+source_conf_file() {
+  unqualified_name="$1"
+  if [[ -n $unqualified_name ]]; then
+    filename="$unqualified_name"
+    if [[ ${filename:0:1} != '/' ]]; then
+      filename="${USER_BACKUP_CONFDIR}"/"${filename}"
+    fi
+    source "$filename" || abort
+  fi
+}
+
 init() {
-  options=$(getopt --longoptions "help,envfile:" -- "" "$@")
-  if [ $? -ne 0 ] # Problem with getting options?
-  then
+  options=$(getopt --name "$NAME" --longoptions "help,envfile:" -- "" "$@")
+  # shellcheck disable=SC2181
+  if [[ $? -ne 0 ]]; then # Problem with getting options?
     show_help
+    die 1
   fi
 
   # Sets double dashes, which marks end of optional parameters
@@ -41,28 +54,30 @@ init() {
 
   while true; do
     case $1 in
-      '--envfile')
-        ${2:0:1} != '-' || abort "$1 requires a filename argument"
+    '--envfile')
+        [[ ${2:0:1} != '-' ]] || abort "$1 requires a filename argument"
         envfile="$2"
         shift 2
       ;;
-      '--help')
+    '--help')
         show_help
         die 0
       ;;
-      --) # Separator between optional and positional parameters
+    '--')   # Separator between optional and positional parameters
         shift
         break
-        ;;
+      ;;
     esac
   done
 
   paths_on_cmdline=( "$@" )
   set --
 
-  if [[ -n $envfile ]]; then
-    source "$envfile" || abort
-  fi
+  source_conf_file "$envfile"
+
+  # HOOKS is exptected to be set in the envfile
+  source_conf_file "$HOOKS"
+
   # PATHS_TO_BACKUP can come from $envfile, but files on command line overrides
   if [[ ${#paths_on_cmdline[*]} -gt 0 ]]; then
     PATHS_TO_BACKUP=( "${paths_on_cmdline[@]}" )
@@ -73,6 +88,19 @@ init() {
 
 ## main
 init "$@"
+
+info "$NAME starting"
+trap 'info "$NAME ending"' EXIT
+
+if [[ $(type -t post_backup) == 'function' ]]; then
+  # use trap: in case 'borg create' fails we still want to restore system to production mode
+  trap 'info "Running post-backup hook" ; post_backup ; info "$NAME ending"' EXIT
+fi
+
+if [[ $(type -t pre_backup) == 'function' ]]; then
+  info "Running pre-backup hook"
+  pre_backup
+fi
 
 info "Starting borg backup"
 
