Print info on warning/failure from borgbackup-job
removing errexit, keeping logic
The use of errexit makes the code providing info on warning/exit unreachable,
since the non-zero exit code it checks would already have exited the script.

diff --git a/borgbackup-job b/borgbackup-job
--- a/borgbackup-job
+++ b/borgbackup-job
@@ -1,11 +1,11 @@
 #!/bin/bash
 
-set -o errexit
-
 PATHS_TO_BACKUP=("$@")
 
 # Some helpers and error handling
 info() { printf "\n%s %s\n\n" "$( date )" "$*" >&2; }
+die() { rc=$1; shift; info "$*"; exit "$rc" ;}
+warning_or_error() { code=$1; ret="warning"; [[ $code -gt 1 ]] && ret="error"; echo $ret; }
 trap 'echo $( date ) Backup interrupted >&2; exit 2' INT TERM
 
 info "Starting borg backup"
@@ -18,9 +18,7 @@ borg create                       \
      --list                       \
                                   \
      ::'{now:%Y-%m-%dT%H:%M:%S}'  \
-     "${PATHS_TO_BACKUP[@]}"
-
-backup_exit=$?
+     "${PATHS_TO_BACKUP[@]}" || die $? "borg create resulted in $(warning_or_error $?). Exiting"
 
 info "Pruning repository"
 
@@ -30,21 +28,4 @@ borg prune             \
     --keep-daily    14 \
     --keep-weekly   4  \
     --keep-monthly  12 \
-    --keep-yearly   5  \
-
-prune_exit=$?
-
-# use highest exit code as global exit code
-global_exit=$(( backup_exit > prune_exit ? backup_exit : prune_exit ))
-
-if [ ${global_exit} -eq 1 ];
-then
-    info "Backup and/or Prune finished with a warning"
-fi
-
-if [ ${global_exit} -gt 1 ];
-then
-    info "Backup and/or Prune finished with an error"
-fi
-
-exit ${global_exit}
+    --keep-yearly   5   || die $? "borg prune resulted in $(warning_or_error $?). Exiting"
